### ISSUE TITLE
[FEATURE] run bpfvalidator against kernels not fetched from the Ubuntu mainline

### ISSUE THREAD

**Issue by Andreagit97** [Andreagit97/bpfvalidator#14]
Today `bpfvalidator` always calls virtme-ng binary in this form `vng -r <kernel-version>`. This is ok until we use precompiled kernels fetched from the Ubuntu mainline.
In the future, we could download pre-built kernels from other locations. Moreover, we should allow the user to call virtme-ng with any arguments that make sense in this context, like `--force-9p` if the kernel doesn't support `virtiofs`

To address the above issues, we could turn the `kernel_versions` key from something like this

```yaml
kernel_versions:
    - v5.4.293
    - v5.10.237
    - v5.15.182
```

Into something like this:

```yaml
kernel_versions:
    - remote:  v5.4.293 # if it starts with `v` we will download from ubuntu mainline
      vng_args: "--force-9p"
    - remote: https://... # we will download a tar from somewhere, untar it and run virtme-ng into that folder
      vng_args: ""
```
